# .github/workflows/docker-publish.yml
name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: netshoot-screen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker tags
      id: vars
      run: |
        echo "REPO=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
        echo "TAG_LATEST=latest" >> $GITHUB_ENV
        echo "TAG_COMMIT=${GITHUB_SHA::7}" >> $GITHUB_ENV
        echo "TAG_VERSION=v1.0.0" >> $GITHUB_ENV  # можно заменить на динамическую версию

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REPO }}:${{ env.TAG_LATEST }}
          ${{ env.REPO }}:${{ env.TAG_COMMIT }}
          ${{ env.REPO }}:${{ env.TAG_VERSION }}
